workflows:
  flutter-android:
    name: Build Android App
    max_build_duration: 60
    environment:
      flutter: 3.22.0
      xcode: latest
      java: 17
      vars:
        BUILD_MODE: debug
    scripts:
      - name: Set up Flutter dependencies
        script: |
          flutter pub get
      - name: Build Android App Bundle (.aab)
        script: |
          flutter build appbundle --debug
    artifacts:
      - build/app/outputs/bundle/debug/app-debug.aab
    cache:
      cache_paths:
        - ~/.pub-cache
        - build
