workflows:
  build-apk:
    name: Build Signed APK
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - release-keystore
      vars:
        CM_KEYSTORE_PATH: /tmp/keystore.jks
        CM_KEYSTORE_PASSWORD: Tech@dm1n123
        CM_KEY_ALIAS: my-key-alias
        CM_KEY_PASSWORD: Tech@dm1n123
    scripts:
      - name: Decode keystore
        script: echo $CM_KEYSTORE | base64 --decode > $CM_KEYSTORE_PATH
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
