name: cloud_pos_flutter
description: "A Flutter project for Cloud POS."
publish_to: 'none' # Prevents accidental publishing to pub.dev.

version: 1.0.0+1 # Follow https://semver.org.

environment:
  sdk: ">=3.8.0 <4.0.0" # As suggested by `flutter pub get` to resolve its error.
  flutter: ">=3.22.0" # Ensure an active Flutter SDK constraint. Adjust if a different minimum Flutter version is intended.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Dependencies are sorted alphabetically for better readability and maintenance.
  app_settings: ^6.1.1
  badges: ^3.1.2
  barcode_scan2: ^4.3.0
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.1.4
  cron: ^0.6.2 # Downgraded as per `flutter pub get` suggestion, was ^0.7.0
  dio: ^5.4.3+1
  flutter_html_to_pdf: ^0.7.0
  fluttertoast: ^8.2.5
  geolocator: ^14.0.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.1
  http: ^1.2.1
  image_picker: ^1.1.1
  material_design_icons_flutter: ^7.0.7296
  path_provider: ^2.1.3
  pdf: ^3.10.8
  permission_handler: ^12.0.0+1
  printing: ^5.12.0
  provider: ^6.1.2
  qr: ^3.0.1
  share_plus: ^11.0.0
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  syncfusion_flutter_datepicker: ^29.2.5
  url_launcher: ^6.2.6
  video_player: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Dev dependencies are sorted alphabetically after flutter_test.
  flutter_launcher_icons: ^0.14.3

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
