name: pos_2
description: A new Flutter application.

publish_to: 'none' 

version: 1.5.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: any
  app_settings: ^6.1.1
  badges: ^3.1.2
  barcode_scan2: ^4.3.0
  cached_network_image: ^3.3.1
  change_app_package_name: ^1.1.0
  connectivity_plus: ^6.1.4 
  cron: ^0.6.0
  dio: ^5.4.3+1
  flutter_html_to_pdf: ^0.7.0
  fluttertoast: ^8.2.5
  geolocator: ^14.0.1
  get_ip_address: ^0.0.6
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.1
  http: ^1.2.1
  image_picker: ^1.1.1
  material_design_icons_flutter: ^7.0.7296
  path_provider: ^2.1.3
  pdf: ^3.10.8
  permission_handler: ^12.0.0+1
  printing: ^5.12.0
  provider: ^6.1.2
  qr: ^3.0.1
  sqflite: ^2.3.3+1
  shared_preferences: ^2.2.3
  search_choices: ^2.2.1
  share_plus: ^11.0.0 
  syncfusion_flutter_datepicker: ^29.2.5
  url_launcher: ^6.2.6
  video_player: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/TM Tech POS.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - i18n/